### ISSUE TITLE
i want you to merge v2.16.1g

### ISSUE THREAD

**Issue by etsuyoshi** [cyber-z/public-fox-ios-sdk#11]
pod "foxSdk", :podspec => "https://github.com/cyber-z/public-fox-ios-sdk/raw/v2.16.1g/cocoapods/foxSdk.podspec"

[!] Failed to fetch podspec for `foxSdk` at `https://github.com/cyber-z/public-fox-ios-sdk/raw/v2.16g.1/cocoapods/foxSdk.podspec`.
 Error: 404 Not Found

**Comment by czkadota** [comment]
Issue Thank you very much .
It is currently supported already .
The document is incomplete , but I will support later .
