### ISSUE TITLE
File name conflicts with standard library.

### ISSUE THREAD

**Issue by RyogaK** [cyber-z/public-fox-ios-sdk#23]
You are using `Notify.h` that you made but Apple supplies `notify.h` in standard.
If Notify.h of fox is there, I can't use `#import <notify.h>`.
In accordance with customary practice, you should use prefix like `FOXNotify.h`.

Thanks.

**Comment by czwuwei** [comment]
Yes, thank you for pointing this out.
We have decided to remove this file in the future version to fix this.

If you are not using file `Notify.h` for this time, 
would you mind to remove it from the header search path?

**Comment by RyogaK** [comment]
The conflict is caused in a project that generated by cocoapods. So this time, I gonna remove FOX from Podfile and put files manually into my project.

Thank you for your quick reply.
